# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-08 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='dashboard.Book'),
        ),
    ]
